/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.hiteshlilhare.jcplaystore.test;

import java.awt.FlowLayout;
import java.awt.event.ActionListener;

/**
 *
 * @author Hitesh
 */
public class AppButtonPanel extends javax.swing.JPanel {

    /**
     * Creates new form AppButtonPanel2
     */
    public AppButtonPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateButton = new javax.swing.JButton();
        installButton = new javax.swing.JButton();
        downloadButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 5, 0));

        updateButton.setBackground(new java.awt.Color(255, 255, 255));
        updateButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update_icon_1_32.png"))); // NOI18N
        updateButton.setToolTipText("Update");
        updateButton.setBorder(null);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton);

        installButton.setBackground(new java.awt.Color(255, 255, 255));
        installButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        installButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/install_icon_1_32.png"))); // NOI18N
        installButton.setToolTipText("Install");
        installButton.setBorder(null);
        installButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installButtonActionPerformed(evt);
            }
        });
        add(installButton);

        downloadButton.setBackground(new java.awt.Color(255, 255, 255));
        downloadButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        downloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download_icon_32.png"))); // NOI18N
        downloadButton.setToolTipText("Download");
        downloadButton.setBorder(null);
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });
        add(downloadButton);

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_icon_1_32.png"))); // NOI18N
        deleteButton.setToolTipText("Uninstall/Delete");
        deleteButton.setBorder(null);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void installButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_installButtonActionPerformed

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downloadButtonActionPerformed

    public void setButtonVisibility(boolean[] diudFlags){
        //visibility flag 0-delete,1-install,2-update,3-download button
        deleteButton.setVisible(diudFlags[0]);
        installButton.setVisible(diudFlags[1]);
        updateButton.setVisible(diudFlags[2]);
        downloadButton.setVisible(diudFlags[3]);
    }
    
    public void addDeleteButtonActionListener(ActionListener listener){
        deleteButton.addActionListener(listener);
    }
    
    public void addUpdateButtonActionListener(ActionListener listener){
        updateButton.addActionListener(listener);
    }
    
    public void addInstallButtonActionListener(ActionListener listener){
        installButton.addActionListener(listener);
    }
    
    public void addDownloadButtonActionListener(ActionListener listener){
        downloadButton.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton downloadButton;
    private javax.swing.JButton installButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
