/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.hiteshlilhare.jcplaystore;

import com.github.hiteshlilhare.jcplaystore.test.AppPanelCellEditor;
import com.github.hiteshlilhare.jcplaystore.test.AppPanelCellRenderer;
import com.github.hiteshlilhare.jcplaystore.test.AppPanelTableModel;
import com.github.hiteshlilhare.jcplaystore.ui.util.ModernScrollPane;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Hitesh
 */
public class InstalledAppPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form InstalledAppPanel1
     */
    public InstalledAppPanel1() {
        initComponents();
        table = new JTable(new AppPanelTableModel());
        
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        table.getTableHeader().setUI(null);
        table.setShowGrid(false);
        
        Dimension dim = new Dimension(20, 8);
        table.setIntercellSpacing(new Dimension(dim));
        table.setDefaultRenderer(AppPanel.class, new AppPanelCellRenderer());
        table.setDefaultEditor(AppPanel.class, new AppPanelCellEditor());
        table.setRowHeight(215);
//        ModernScrollPane modernScrollPane = new ModernScrollPane(table);
//        modernScrollPane.setViewportView(table);        
//        add(modernScrollPane);
         pane= new JScrollPane(table,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        pane.getViewport().setBackground(Color.BLUE);
        add(pane);
    }

    public void addAppPanel(AppPanel app) {
        ((AppPanelTableModel) table.getModel()).addColumn(app);
        TableColumnModel columnModel = table.getColumnModel();
        int count = columnModel.getColumnCount();
        System.out.println("column count = " + count);
        for (int i = 0; i < count; i++) {
            columnModel.getColumn(i).setPreferredWidth(190);
            columnModel.getColumn(i).setMaxWidth(190);
            columnModel.getColumn(i).setMinWidth(190);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Installed Apps", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 867, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private JTable table;
    JScrollPane pane;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
