/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.hiteshlilhare.jcplaystore;

import com.github.hiteshlilhare.jcplaystore.ui.util.Config;
import info.clearthought.layout.TableLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Hitesh
 */
public class RepositorySettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form RepositorySettingsPanel
     */
    public RepositorySettingsPanel() {
        initComponents();
        double border = 10;
        double size[][]
                = {{border, 150, TableLayout.FILL, 90, border}, // Columns
                {border, 25, border, 25, border, 25, border}}; // Rows
        repositoryPanel.setLayout(new TableLayout(size));
        repositoryPanel.add(remoteRepoUrlLabel, "1,1");
        repositoryPanel.add(localAppDirLabel, "1,3");
        repositoryPanel.add(urlTextField, "2,1,3,1");
        repositoryPanel.add(localDirTextField, "2,3");
        repositoryPanel.add(browseButton, "3,3");
        repositoryPanel.add(applyButton, "3,5");
        localDirTextField.setEditable(false);
        browseButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                JFileChooser fileChooser = new JFileChooser(JCConstants.JC_APP_BASE_DIR);
                fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                fileChooser.setMultiSelectionEnabled(false);
                int r = fileChooser.showOpenDialog(null);
                if (r == JFileChooser.APPROVE_OPTION) {
                    localDirTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
                }
            }
        });
        applyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Config.setLocalAppDir(localDirTextField.getText());
                Config.setServerUrl(urlTextField.getText());
                Config.save();
            }
        });
        
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        repositoryPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout repositoryPanelLayout = new javax.swing.GroupLayout(repositoryPanel);
        repositoryPanel.setLayout(repositoryPanelLayout);
        repositoryPanelLayout.setHorizontalGroup(
            repositoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        repositoryPanelLayout.setVerticalGroup(
            repositoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(repositoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(repositoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel repositoryPanel;
    // End of variables declaration//GEN-END:variables
    JLabel remoteRepoUrlLabel = new JLabel("Remote Repository URL:");
    JTextField urlTextField = new JTextField(Config.getServerUrl());
    JLabel localAppDirLabel = new JLabel("Local App Dir:");
    JTextField localDirTextField = new JTextField(Config.getLocalAppDir());
    JButton browseButton = new JButton("Browse");
    JButton applyButton = new JButton("Apply");
}
