/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.hiteshlilhare.jcplaystore.ui.mainframe;

import info.clearthought.layout.TableLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author Hitesh
 */
public class LicensePanel extends javax.swing.JPanel {

    /**
     * Creates new form LicensePanel
     */
    public LicensePanel() {
        initComponents();
        initialize();
    }
    
    public void setPgressBarValue(int value){
        progressBar.setValue(value);
    }
    
    public void showProgressBar(boolean show){
        progressBar.setVisible(show);
    }
    
    private void initialize(){
        setBackground(new java.awt.Color(255, 255, 255));
        progressBar = new JProgressBar();
        progressBar.setValue(0);
        progressBar.setStringPainted(true);
        progressBar.setVisible(false);
        
        licenseLabel = new JLabel("MIT License");
        licenseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mit_license.png")));

        licenseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        double size[][]
                = {{TableLayout.FILL}, // Columns
                {10, 20 ,5,TableLayout.FILL}}; // Rows
        setLayout(new TableLayout(size));
        add(progressBar,"0,1");
        add(licenseLabel,"0,3");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private JProgressBar progressBar;
    private JLabel licenseLabel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
